version: '3'
services:
  web: &web
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: python manage.py runserver --settings=microservice.settings.dev 0.0.0.0:70 
    depends_on:
      - mysql
      - redis
    ports:
      - 70:70
    volumes:
      - ./app:/app

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: "hakan"
      MYSQL_PASSWORD: "485861"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: "redis:alpine"

  celery_worker:
    <<: *web
    command: celery -A microservice worker --loglevel=info
    ports: []
    depends_on:
      - mysql
      - redis
volumes:
  mysql-volume: