pipeline { 
    agent any 
    stages {
        stage('Build') { 
            steps { 
                sh 'cd' 
            }
        }
        stage('Test'){
            steps {
                sh 'cd'
            }
        }
        stage('Deploy') {
            steps {
                sh 'ls'
            }
        }
    }
}
